"""
Django settings for djangocrud project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

# settings.py
from pathlib import Path
import os # librería para intereactuar con el sistema operativo



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent #define la ruta base del proyecyo usando Path,  apunta a "djangocrud"


# CONFIGUARCIÓN DE DIRECTORIOS PARA ARCHIVOS ESTÁTICOS (css,js, cosas "no volátiles")
STATIC_URL = '/static/' # url basica para poder acceder a los archivos estáticos
STATICFILES_DIRS = [BASE_DIR / "static"] #directorio en donde se encuentarn los arhivos estáticos para desarrollo (cuando la pagina es accesible solo al local)
STATIC_ROOT = BASE_DIR / "staticfiles" #directorio en donde se encuentarn los arhivos estáticos para prducción (cuando la pagina es accesible para usuarios)


# CONFIGURACIÓN DE DIRECTORIOS PARA ARCHIVOS MULTIMEDIA (subidos por el usuario, "volátiles")
MEDIA_URL = '/media/' # url básico para acceder a los archivos multimedia 
MEDIA_ROOT = BASE_DIR / "media" #directorio en donde se encuentra los archivos multimedia que son subidos por el usuario (producción)


# CONFIGURACIÓN PARA EL INICIO DE SESIÓN
LOGIN_URL = '/login/'# los usarios que no están registrados e intentant acceder a vistas protegidas son redirigidos al login

# MODELO PERSONALIZADO PARA CREAR USUARIOS
AUTH_USER_MODEL = 'tasks.Usuario' # la aplicación tasks crea usuarios a partir del modelo Usuario



SECRET_KEY = 'django-insecure-lv2gqmc)cz(&v_--wz6x3lqi2^-#ug_o3fz=s00a+hi3bm6j_i'# tiene como función asegurar la integridad de los datos, firma cookies para evitar q sean manipuladas

# PRODUCCIÓN / DESARROLLO

#DEBUG = False # esto significa que está en producción
DEBUG = True #para correr en local, siginifa que está en desarrollo
#ALLOWED_HOSTS = ['proyectointa.onrender.com']#lo usaba con render.com
# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin', # app de django para el panel de administración
    'django.contrib.auth', # sistmea de autenticación de django
    'django.contrib.contenttypes', # soporte para tipod de modelos
    'django.contrib.sessions', #gestion de sesiones
    'django.contrib.messages', # framework de mensajes
    'django.contrib.staticfiles', # manejo de archivos estáticos
    'tasks', #nuestra aplicación personalizada tasks

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CONFIGURACIÓN DE URLs
ROOT_URLCONF = 'djangocrud.urls' # archivo principal que maneja todas las urls de la aplicación

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # 'DIRS' es una lista para definir rutas adicionales en donde django despues va a buscar plantillas, si no hay nada, busca en las applicaciones de "INSTALLED_APPS"
        #le indica a django donde buscar las plantillas html, En este caso es en "templates" ubicada en directorio raiz del proyecto (base_dir)
        
        'APP_DIRS': True, #indica que debe buscar plantillas dentro de cada aplicación instalada
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangocrud.wsgi.application'# protoclo que permite que un servidor se comunique con Django por medio de solicitudes http


# configuración de la base de datos, por defecto es slqlite3
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', #motor de la base de datos
        'NAME': BASE_DIR / 'db.sqlite3',#archivo de la base de datoss
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# VALIDADORES DE CONTRASEÑAS
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',#verifica que la contraseña no sea muy similar an usuario/email/x campo
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',# verifica la cantidad de caracteres, en este caso son mínimo 5
        'OPTIONS': {
            'min_length': 5,  
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', #verifica que la contraseña no sean cadenas seguidas como 1234 o qwerty
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', #verifica que la contraseña no sea solo números
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# CONFIGUARCIÓN DE IDIOMA Y ZONA HORARIA
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Esto asegura que Django sirva los archivos estáticos correctamente
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





#TODO ESTO DE EMAIL NO LO ESTAMOS USANDO PARA NADA

#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.sendgrid.net'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'apikey'  # Este es el usuario fijo para SendGrid
#EMAIL_HOST_PASSWORD = 'jasjdnfiaeqowj234'
#DEFAULT_FROM_EMAIL = 'matiaslang124@gmail.com'
